apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::380321707316:role/eksctl-eksctl-demo-nodegroup-ng-5-NodeInstanceRole-9V6QLQP74UT7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::380321707316:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-07T17:39:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1896"
  uid: 94ab974c-0fa4-4413-985b-9c85be3cbb68
